FROM php:8.2-fpm

# Установка зависимостей
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpq-dev \
    libzip-dev \
    unzip \
    && docker-php-ext-install pdo pdo_pgsql zip

# Установка Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Рабочая директория
WORKDIR /var/www

# Копируем код и устанавливаем зависимости
COPY . .



RUN composer install

RUN composer update --no-interaction --no-progress

# Права для storage
RUN chown -R www-data:www-data /var/www/storage
RUN chmod -R 775 /var/www/storage


CMD ["php-fpm"]


COPY .env.example .env

ENTRYPOINT ["init.sh"]
RUN  php artisan key:generate --force
